<a href="https://colab.research.google.com/github/iLikeKatz/MyLeaning_ML/blob/main/PytorchFullCourse/Tensor/TensorManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Topic

*   Reshaping

*   View

*   Stacking

*  Squeeze

* Unsqueen

* Permute



In [ ]:
import torch

In [ ]:
x = torch.arange(1, 10)
x.shape

torch.Size([9])

### Reshape

In [ ]:
#reshape
xReshaped = x.reshape(9, 1) #x * y must be = x.shape
xReshaped.shape

torch.Size([9, 1])

### View

In [ ]:
#view (the difference is z will share memory with x, so if x is changed, z follow x)
z = x.view(9, 1)
x = x + 1
z

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

### Stack

In [ ]:
#Stack tensor
xStacked = torch.stack([x, x, x], dim = 0)
xStacked #x stacked by x and x in dim 0

tensor([[ 2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
#Stack tensor (dim 1)
xStackedDim1 = torch.stack([x, x, x], dim=1)
xStackedDim1 #x stacked by x and x in dim 1

tensor([[ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]])

### Squeeze

In [ ]:
#Squeeze remove single dimension, like, if shape : [3, 1] (2d) then use squeen and it'll  reshape to : [3] (1d)
a = torch.rand(3, 1)
a.ndim,  a.squeeze().ndim

(2, 1)

### Unsqueeze

In [ ]:
#Unsqueeze is opposite of squeeze, it's use to add dimen to tensors (if a tensor is single dimen)
b = torch.rand(3)
f"{b.ndim} dim  to { b.unsqueeze(1 or 0).ndim} dim"


'1 dim  to 2 dim'

In [ ]:
#the difference of unsquuze dim 0 and 1
print(f"dim 0 : {b.unsqueeze(0).shape} (add rows 1rows 3columns), \n dim 1 : {b.unsqueeze(1).shape} (add columns, 3rows 1columns)")

dim 0 : torch.Size([1, 3]) (add rows 1rows 3columns), 
 dim 1 : torch.Size([3, 1]) (add columns, 3rows 1columns)


### Permute

In [ ]:
g = torch.randn(2, 3, 4)
g.shape

torch.Size([2, 3, 4])

In [ ]:
g.permute( (2, 0, 1)).shape #based on index, it's mean you swap dimension by index
#index 2 > 0, index 0 > 1, index1 > 2, so 2, 3, 4 > 4, 2, 3

torch.Size([4, 2, 3])

### Reproducibility

In [170]:
#Reproducibility
randomSeed = 42 #whatever but 42 is popular
torch.manual_seed(randomSeed)
RandTens1 = torch.rand(3, 2)

torch.manual_seed(randomSeed)
RandTens2 = torch.rand(3, 2)
print(RandTens1 == RandTens2)

#กล่าวคือ เมื่อนำ randomseed เลขเดยวกัน ไปวางไว้ด้านบน block ของ randomTens มันจะทำให้ค่า random ออกมาเท่ากันเสมอ

tensor([[True, True],
        [True, True],
        [True, True]])
