<a href="https://colab.research.google.com/github/iLikeKatz/MyLeaning_ML/blob/main/PytorchFullCourse/Tensor/WhatIsTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as non
import numpy as np
import pandas

# **อธิบายก่อน คร่าวๆ**

scalar คือจำนวน จำนวนเดียว ไม่มีมิติ

vector คือกลุ่มจำนวนหลายจำนวน มีมิติเดียว

matrix คือกลุ่มจำนวนหลายจำนวน มี2มิติ rows, columns

tensor คือกลุ่มจำนวนหลายจำนวน เป็นไปได้ตั้งเเต่ 0 ถึง infมิติ

เเต่มักถูกเรียกตอน 3มิติขึ้นไป

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim #check dimens, scalars always have 0 dimen and only 1 number

0

In [ ]:
#transform tensor to int (only scalar can)
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([1,2,3])
vector


tensor([1, 2, 3])

In [ ]:
vector.ndim #vectors always have 1 dimen

1

In [ ]:
#Matrix
mat = torch.tensor([[1,2], [3,4]])
mat

tensor([[1, 2],
        [3, 4]])

In [ ]:
mat.ndim #matrixs always have 2 dimens

2

In [ ]:
#tensor
tens = torch.tensor([[[1,2,3], [4,6,6], [6,7,9]]])
tens

tensor([[[1, 2, 3],
         [4, 6, 6],
         [6, 7, 9]]])

In [ ]:
tens.ndim #and yeah tensors always have 3d or higer

3